# Generated by Django 4.2.9 on 2024-03-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_trains_date'),
        ('trains', '0004_auto_20210428_0239'),
    ]

    operations = [
    ]
